# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a75f1d26b97061e1719194cb606fd7308fe0cab35efdf355dcc73078a4c4540106bcdb57bdc802127615ee9b59eca35c5012da8cb978c698cbfd6af2e04ad3f

test:
  secret_key_base: 6beb2d7a00d7493874174c3617d01386e09cbe76ec739917c1403b9ec62fb606f14e2387c1da420bdceef40ce7c3cfb6f50010c5644bab52da39169c3cc50024

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
